[db]
pathfinder_name = "pathfinder"
universe_name = "eve_universe"
user = "root"
password = "somepassword"
host = "localhost"
port = 3306

[watcher]
loglevel = "INFO"
refresh = 6 # After how many seconds the systems should be refreshed
mapid = 1
filter_corporations = [
	98658535,
]
filter_if_victim = true # Should the killmail be ignored if the victims corp was listed in filter_corporations

[discord]
bot_token = "Nzc2NzkyODI0NDgxMDU0NzUw.X66CsQ.YQuWPVESjrXReCRaTKlXWnmCYUU"
channel_id = 776794537955557449
